### ISSUE TITLE
It is possible to gain access to other players' homes.

### ISSUE THREAD

**Issue by BlueFoxyy** [Xquiset/SetHomesTwo#6]
#### Description
As title.

#### To Reproduce
Plugin version: 1.0.1
Minecraft server version: 1.20.4
CraftBukkit version: 4018-Spigot-864e4ac-95bc1c4 (1.20.4-R0.1-SNAPSHOT)

Steps:
1. Have a freshly installed server with SetHomesTwo and LuckPerms (or give operator permission `/op`) installed.
2. Have two people (player A and player B) log onto the server.
3. Have them create `home_A` and `home_B` respectively and run `/give-homes-item`
4. First, let player A open their home gui, then let player B open their gui.
5. Now player A should be able to select player B's `home_B` and teleport to their set home.

**Comment by milanmalhotra** [comment]
Hey BlueFoxyy, we'll take a look into this!

**Comment by Xquiset** [comment]
Thanks for the well documented explanation. We have now committed the fix to GitHub, and are just waiting on curse forge to accept the new version file. Should be up on their site within the next few days. Cheers!
