### ISSUE TITLE
pom.xml; commons-lang

### ISSUE THREAD

**Issue by lumpynose** [Xquiset/SetHomesTwo#7]
I think commons-lang3 is a drop in replacement for the commons-lang 2 that you're using.  If you use commons-lang3 then you can add the scope provided.  But I'm essentially clueless about which servers a plugin will work with.

https://www.spigotmc.org/wiki/included-libraries-in-spigot/

**Comment by Xquiset** [comment]
Thank you for the info. I have updated our pom file. Cheers!
