### ISSUE TITLE
substring

### ISSUE THREAD

**Issue by lumpynose** [Xquiset/SetHomesTwo#8]
https://github.com/Xquiset/SetHomesTwo/blob/d39f1851df39c2fe83a9f4e540ef18916327e487/src/main/java/com/samleighton/sethomestwo/connections/BlacklistConnection.java#L58-L61

Instead of doing substring instead you could do

`    stringBuilder.append("(?)");`

before the for loop, and start the for loop with i=1,  and append ",(?)" on each iteration.  And not do the initial append (or any of it) if dimensionNames.size() == 0 (if it could be 0).

**Comment by Xquiset** [comment]
This was changed with latest dao pattern update.
