### ISSUE TITLE
jdbc dao pattern

### ISSUE THREAD

**Issue by lumpynose** [Xquiset/SetHomesTwo#9]
Here's a nice writeup on the dao pattern.

[https://www.baeldung.com/java-dao-pattern](https://www.baeldung.com/java-dao-pattern)

If you could use that for your database stuff then I'd be interested in trying to make it work with MongoDB, which I've never used, so it would be an interesting learning experiment for me. (Even though I hate json.)

**Comment by Xquiset** [comment]
Hey there

I believe that I have now gotten everything converted over to a dao pattern. Take a look at master branch and let me know what you think. Thanks for the suggestion 👍 

Xquiset
